version: '3.7'

networks:
  n-database:
    driver: bridge
  n-frontend:
    driver: bridge

volumes:
  v-database:

services:
  s-database:
    container_name: c-database
    image: postgres:15.1-alpine3.16
    networks:
      - n-database
    environment:
      - POSTGRES_USER=wsstore
      - POSTGRES_DB=wsstore
      - POSTGRES_PASSWORD=1234
    volumes:
      - v-database:/var/lib/postgresql/data
      - ./script:/script
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  s-backend:
    depends_on:
      - s-database
    container_name: c-backend
    image: python:3.11.0-alpine3.16
    networks:
      - n-database
      - n-frontend
    environment:
      - SECRET_KEY=df1e2ed064189acdcd83cb5ddf230580c0efdff7f2974a13cd16e1c8c9dd
      - DATABASE_URL=postgresql+psycopg2://wsstore:1234@s-database:5432/wsstore
    entrypoint: sh
    working_dir: /backend
    volumes:
      - ./backend/:/backend
    ports:
      - 5000:5000
    command: ./app.sh

  s-frontend:
    container_name: c-frontend
    image: node:19-alpine3.16
    networks:
      - n-frontend
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 4200:4200
    command: sh -c 'npm install -g npm@9.1.2 @angular/cli@15.0.0 && ng serve --host='0.0.0.0' --port=4200'